[package]
name = "pinout"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
csv = "1.3.1"
image = "0.25.6"
serde = { version = "1.0.219", features = ["derive"] }
svg = "0.18.0"
thiserror = "2.0.12"
